---
- name: Deploy Animal's Sounds Application to localhost
  hosts: localhost

  vars:
    home: /opt/flask-app
    directory: /opt/flask-app/ansible_hw

  tasks:
  - name: Clone repo
    git: >
      repo=https://github.com/tuumaan/devops-andersen.git
      dest={{home}}

  - name: Install pip
    apt:
      name: python3-pip
      update_cache: no
      state: present

  - name: Install Flask
    pip: 
      requirements: "{{directory}}/requirements.txt"
      executable: pip3

  - name: huyak
    shell:
      cmd: "touch {{directory}}/__init__.py"

  - name: Run Flask Application
    shell:
      cmd: "python3 {{directory}}/app.py"

...
