emodji = \
{
    "monkey":"🐒",
    "gorilla":"🦍",
    "orangutan":"🦧",
    "dog":"🐕",
    "guide dog":"🦮",
    "service dog":"🐕‍🦺",
    "poodle":"🐩",
    "wolf":"🐺",
    "fox":"🦊",
    "raccoon":"🦝",
    "cat":"🐈",
    "black cat":"🐈‍⬛",
    "lion":"🦁",
    "tiger":"🐅",
    "leopard":"🐆",
    "horse face":"🐴",
    "horse":"🐎",
    "unicorn":"🦄",
    "zebra":"🦓",
    "deer":"🦌",
    "bison":"🦬",
    "ox":"🐂",
    "buffalo":"🐃",
    "cow":"🐄",
    "pig":"🐖",
    "boar":"🐗",
    "ram":"🐏",
    "ewe":"🐑",
    "goat":"🐐",
    "camel":"🐪",
    "two-hump camel":"🐫",
    "llama":"🦙",
    "giraffe":"🦒",
    "elephant":"🐘",
    "mammoth":"🦣",
    "rhinoceros":"🦏",
    "hippopotamus":"🦛",
    "mouse":"🐁",
    "rat":"🐀",
    "hamster":"🐹",
    "rabbit":"🐇",
    "chipmunk":"🐿️",
    "beaver":"🦫",
    "hedgehog":"🦔",
    "bat":"🦇",
    "bear":"🐻",
    "polar bear":"🐻‍❄️",
    "koala":"🐨",
    "panda":"🐼",
    "sloth":"🦥",
    "otter":"🦦",
    "skunk":"🦨",
    "kangaroo":"🦘",
    "badger":"🦡",
    "turkey":"🦃",
    "chicken":"🐔",
    "rooster":"🐓",
    "baby chick":"🐤",
    "bird":"🐦",
    "penguin":"🐧",
    "dove":"🕊️",
    "eagle":"🦅",
    "duck":"🦆",
    "swan":"🦢",
    "owl":"🦉",
    "dodo":"🦤",
    "feather":"🪶",
    "flamingo":"🦩",
    "peacock":"🦚",
    "parrot":"🦜",
    "frog":"🐸",
    "crocodile":"🐊",
    "turtle":"🐢",
    "lizard":"🦎",
    "snake":"🐍",
    "dragon":"🐉",
    "sauropod":"🦕",
    "t-rex":"🦖",
    "whale":"🐋",
    "dolphin":"🐬",
    "seal":"🦭",
    "fish":"🐟",
    "blowfish":"🐡",
    "shark":"🦈",
    "octopus":"🐙",
    "snail":"🐌",
    "butterfly":"🦋",
    "bug":"🐛",
    "ant":"🐜",
    "honeybee":"🐝",
    "beetle":"🪲",
    "lady beetle":"🐞",
    "cricket":"🦗",
    "cockroach":"🪳",
    "spider":"🕷️",
    "scorpion":"🦂",
    "mosquito":"🦟",
    "fly":"🪰",
    "worm":"🪱",
    "microbe":"🦠",
    "crab":"🦀",
    "lobster":"🦞",
    "shrimp":"🦐",
    "squid":"🦑"
}
